export const reportesIniciales = [
  {
    id: 1,
    usuarioId: "usuario-demo-luna",
    nombreMascota: "Luna",
    tipoMascota: "Perro",
    raza: "Mestiza",
    color: "Blanco con café",
    descripcion:
      "Se perdió cerca del parque central. Es tranquila, responde al nombre de Luna y llevaba un collar rosado.",
    estado: "Perdida",
    estadoReporte: "activo",
    provincia: "Manabí",
    ciudad: "Manta",
    sector: "Ciudadela Universitaria",
    telefono: "0987654321",
    fecha: "03/07/2026",
    creadoEn: "2026-07-03T09:00:00.000Z",
    imagen: "https://images.unsplash.com/photo-1552053831-71594a27632d?w=900",
    latitud: null,
    longitud: null,
    sincronizado: true,
    pendienteSincronizacion: false,
    propio: false,
    avistamientos: [],
    usuarioNombre: "María Zambrano",
    usuarioFoto: null,
  },
  {
    id: 2,
    usuarioId: "usuario-demo-milo",
    nombreMascota: "Milo",
    tipoMascota: "Gato",
    raza: "Criollo",
    color: "Gris",
    descripcion:
      "Fue visto por última vez cerca de una tienda del barrio. Es algo asustadizo.",
    estado: "Perdida",
    estadoReporte: "activo",
    provincia: "Manabí",
    ciudad: "Portoviejo",
    sector: "La Rotonda",
    telefono: "0991234567",
    fecha: "02/07/2026",
    creadoEn: "2026-07-02T11:30:00.000Z",
    imagen: "https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=900",
    latitud: null,
    longitud: null,
    sincronizado: true,
    pendienteSincronizacion: false,
    propio: false,
    avistamientos: [],
    usuarioNombre: "Carlos Vélez",
    usuarioFoto: null,
  },
  {
    id: 3,
    usuarioId: "usuario-demo-max",
    nombreMascota: "Max",
    tipoMascota: "Perro",
    raza: "Labrador",
    color: "Dorado",
    descripcion:
      "El dueño confirmó que Max ya apareció. El reporte queda como historial.",
    estado: "Encontrada",
    estadoReporte: "resuelto",
    provincia: "Manabí",
    ciudad: "Montecristi",
    sector: "Centro",
    telefono: "0977777777",
    fecha: "01/07/2026",
    creadoEn: "2026-07-01T15:20:00.000Z",
    imagen: "https://images.unsplash.com/photo-1561037404-61cd46aa615b?w=900",
    latitud: null,
    longitud: null,
    sincronizado: true,
    pendienteSincronizacion: false,
    propio: false,
    avistamientos: [],
    usuarioNombre: "Andrea López",
    usuarioFoto: null,
  },
  {
    id: 4,
    usuarioId: "usuario-demo-nina",
    nombreMascota: "Nina",
    tipoMascota: "Gato",
    raza: "Siamesa",
    color: "Crema con café",
    descripcion:
      "Se perdió cerca de una panadería. Tiene ojos azules y suele esconderse cuando hay mucho ruido.",
    estado: "Perdida",
    estadoReporte: "activo",
    provincia: "Pichincha",
    ciudad: "Quito",
    sector: "La Floresta",
    telefono: "0965552222",
    fecha: "04/07/2026",
    creadoEn: "2026-07-04T10:10:00.000Z",
    imagen: "https://images.unsplash.com/photo-1533738363-b7f9aef128ce?w=900",
    latitud: null,
    longitud: null,
    sincronizado: true,
    pendienteSincronizacion: false,
    propio: false,
    avistamientos: [],
    usuarioNombre: "Paola Reyes",
    usuarioFoto: null,
  },
  {
    id: 5,
    usuarioId: "usuario-demo-rocky",
    nombreMascota: "Rocky",
    tipoMascota: "Perro",
    raza: "Bulldog",
    color: "Café",
    descripcion:
      "Salió de casa durante la tarde. Es amigable, pero se cansa rápido al caminar.",
    estado: "Perdida",
    estadoReporte: "activo",
    provincia: "Guayas",
    ciudad: "Guayaquil",
    sector: "Alborada",
    telefono: "0951112233",
    fecha: "04/07/2026",
    creadoEn: "2026-07-04T14:20:00.000Z",
    imagen: "https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=900",
    latitud: null,
    longitud: null,
    sincronizado: true,
    pendienteSincronizacion: false,
    propio: false,
    avistamientos: [],
    usuarioNombre: "Jorge Mera",
    usuarioFoto: null,
  },
  {
    id: 6,
    usuarioId: "usuario-demo-coco",
    nombreMascota: "Coco",
    tipoMascota: "Perro",
    raza: "Poodle",
    color: "Blanco",
    descripcion:
      "Se extravió cerca del mercado. Lleva un collar azul y responde cuando le llaman por su nombre.",
    estado: "Perdida",
    estadoReporte: "activo",
    provincia: "Azuay",
    ciudad: "Cuenca",
    sector: "El Vecino",
    telefono: "0983334444",
    fecha: "05/07/2026",
    creadoEn: "2026-07-05T08:35:00.000Z",
    imagen: "https://images.unsplash.com/photo-1597633425046-08f5110420b5?w=900",
    latitud: null,
    longitud: null,
    sincronizado: true,
    pendienteSincronizacion: false,
    propio: false,
    avistamientos: [],
    usuarioNombre: "Lucía Andrade",
    usuarioFoto: null,
  },
  {
    id: 7,
    usuarioId: "usuario-demo-toby",
    nombreMascota: "Toby",
    tipoMascota: "Perro",
    raza: "Mestizo",
    color: "Negro",
    descripcion:
      "Se perdió durante una caminata. Tiene una mancha blanca en el pecho y es muy dócil.",
    estado: "Perdida",
    estadoReporte: "activo",
    provincia: "El Oro",
    ciudad: "Machala",
    sector: "Puerto Bolívar",
    telefono: "0992223344",
    fecha: "05/07/2026",
    creadoEn: "2026-07-05T16:00:00.000Z",
    imagen: "https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=900",
    latitud: null,
    longitud: null,
    sincronizado: true,
    pendienteSincronizacion: false,
    propio: false,
    avistamientos: [],
    usuarioNombre: "Manuel Vera",
    usuarioFoto: null,
  },
];
